source 'https://github.com/CocoaPods/Specs.git'
# source 'http://git.baijiashilian.com/open-ios/specs.git'
source 'git@git.baijiashilian.com:ios/specs.git'

platform :ios, '8.0'
# inhibit_all_warnings!

# [!] [Xcodeproj] Generated duplicate UUIDs:
# @see http://stackoverflow.com/a/33440077/456536
# A:
#   export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES
# B:
#   install! 'cocoapods', :deterministic_uuids => false
install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "BJL"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "BaijiaYun"
end

target 'BJLiveUI' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # dev
    # pod 'BJLiveBase', :path => '../../BJLiveBase/'
    pod 'BJLiveCore', :path => '../../BJLiveCore/'
    pod 'BJLiveUI', :path => '../'
    
    # demo
    pod 'Masonry', :inhibit_warnings => true
    pod 'ReactiveObjC', :inhibit_warnings => true
    
    # debug
    pod 'FLEX', '~> 2.0', :configurations => ['Debug'], :inhibit_warnings => true
    
    target 'BJLiveUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveUIUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
